version: '3'

services:
  pg:
    image: postgres:15-alpine3.20
    environment:
      - "POSTGRES_DB=${DB_DATABASE_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg